# Generated by Django 5.2.4 on 2025-07-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0002_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField()),
                ('password', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
            ],
        ),
        migrations.DeleteModel(
            name='userData',
        ),
    ]
